### ISSUE TITLE
Cannot lock unlocked input

### ISSUE THREAD

**Issue by DavHau** [NixOS/nix#11181]
Not sure if this intentional, but with recent nix versions (using 2.23.x), I cannot persist an input override anymore that points to a local unclean repo.

```
$ nix flake lock --override-input clan-core $HOME/projects/clan/clan-core
warning: will not write lock file of flake [...] because it has an unlocked input ('git+file:///[...]/clan/clan-core')
```

Since nix now defaults to use `--no-write-lock-file` in this case, it is not possible to persist the override.
I found this capability useful, as it allows me to continue operating on the overridden flake, without having to pass `--override-input` every single time.
This is specifically needed, when I operate on the flake via some other tools, which do not support passing extra options to nix.

Though I can see that doing this might be bad practice, as there is a risk of people publishing non-reproducible flakes if that is allowed.
So, not sure if a feature or a bug.

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by roberth** [comment]
We could store a diff in or around the lock file. Such functionality would also benefit https://github.com/NixOS/nix/issues/11160, because unmerged PR commits also have a habit of disappearing.

**Comment by takeda** [comment]
This is a huge regression for me. No longer I can't use `--override-input` I get the same error when also referencing a local directory in `flake.nix`.

Why was this change necessary? Is there a workaround for it?

First we had change that prevented using a relative path and now this. It makes it so much more problematic testing things before making a commit.

**Comment by pwaller** [comment]
Also having the problem here of none of several methods I tried which worked in older versions of nix yielding the ability to override the nixpkgs input of a flake to point to an on-disk work in progress.

* It's also not clear to me how to parse or act on the warning.
  * In what sense is the given input not locked?
  * What should I do to lock it?
  * I'm being given this message while doing `nix flake lock --override-input <input> <override> <input>`, which I would expect to have the effect of addressing the given warning, but that doesn't happen.
* The warning suggests that merely the flake lock was not written, but I suspect from what I'm seeing that in addition to the flake not being written, the specified flake is not being used at all and instead it's being ignored in favour of whatever is in the original lock file. This is not clear from the output.

**Comment by pwaller** [comment]
Workaround for now (newest working version of nix is nix_2_20):
```
nix run nixpkgs#nixVersions.nix_2_20 -- flake lock --override-input nixpkgs git+file:///home/pwaller/.local/src/nixpkgs
```

**Comment by takeda** [comment]
I get it to work, but I had:

1. commit the change
2. make sure there are no uncommitted files when invoking `git status`

If this is not a bug and it was intended to work like that it is really bad idea. Frankly I wish the reverse was possible. I sometimes use nix to set up dev environment and was in places where they did not like when I committed nix files with the project, so it makes really hard to use Nix if the whole team doesn't buy it.

**Comment by lboklin** [comment]
I can't figure out how to fix the problem. I change the input url from a local repo to a remote repo, commit the change, and then run `nix flake update` and I still get the error. What exactly am I supposed to do in this situation?

**Comment by lboklin** [comment]
Furthermore, if I entirely remove the entry from the lock file and run `nix flake lock`, I get `error: lock file references missing node '<input-flake>'`. This must be a bug, surely?

**Comment by RooSoft** [comment]
Also got this error... do I understand that it's now impossible to refer to a local folder with uncommited changes?

I am developing a flake that contains microVM configurations. The local machine can then refer to it with its specific environment, allowing for production, staging, development, etc.... While in development, I got to somehow test those changes, but the flake itself is unuseable without a host. So, I tend to refer to it from a development host to make sure it makes sense before committing new code.

Now, it seems that whenever I create a new microVM configuration, I got to commit untested stuff before I can even try it at all.

Is there a workaround for that specific case?

**Comment by bendlas** [comment]
I am also in dire need for a solution for this. I don't want to create a commit every time I'm trying out a change in a flake I'm referring to ..

**Comment by edolstra** [comment]
As far as I can tell, this is correct behaviour. Lock files should not contain unlocked entries (e.g. dirty Git trees), since that would defeat the whole point of a lock file. However, you can still build flakes with dirty overrides just fine, e.g.
```
# nixos-rebuild build --flake /path/to/flake --override-input nixpkgs /path/to/nixpkgs
warning: Git tree '/path/to/nixpkgs' is dirty
warning: not writing modified lock file of flake 'git+file:///path/to/flake':
....
```
This does not require committing to test a change.

So the solution is: don't use `nix flake lock` when you want to test against a dirty local repo; pass `--override-input` to `nix build` or `nixos-rebuild` instead.

It should probably be an error rather than a warning if `nix flake lock` can't write the lock file.

**Comment by RooSoft** [comment]
Thanks for the info, @edolstra.

Figured out that with `--override-input` applied on `nixos-rebuild switch`, it's not even necessary to run `nix flake update`... the library being worked on seems to be automatically included as it is written to the filesytem.

Makes a lot of sense and solves the issue for me.

**Comment by pwaller** [comment]
> So the solution is: don't use nix flake lock when you want to test against a dirty local repo; pass --override-input to nix build or nixos-rebuild instead.

For what it's worth, I believe that I was trying to do this when I hit the issue. The confusing part is that the message suggests you should try and lock it in that case, but locking also fails, leaving you at a dead end in solution space.

**Comment by RooSoft** [comment]
Obviously, this should be an error, hinting at the `--override-input` solution

**Comment by takeda** [comment]
> As far as I can tell, this is correct behaviour. Lock files should not contain unlocked entries (e.g. dirty Git trees), since that would defeat the whole point of a lock file. However, you can still build flakes with dirty overrides just fine, e.g.
> 
> ```
> # nixos-rebuild build --flake /path/to/flake --override-input nixpkgs /path/to/nixpkgs
> warning: Git tree '/path/to/nixpkgs' is dirty
> warning: not writing modified lock file of flake 'git+file:///path/to/flake':
> ....
> ```
> 
> This does not require committing to test a change.
> 
> So the solution is: don't use `nix flake lock` when you want to test against a dirty local repo; pass `--override-input` to `nix build` or `nixos-rebuild` instead.
> 
> It should probably be an error rather than a warning if `nix flake lock` can't write the lock file.

In my case I was actually using `--override-input` and was pointing to local directory that was not yet committed. In the past it worked but it stopped. Now I had to:

1. create a commit
2. any files that I did not commit I needed to stash

It is harder now to test changes for an dependency before committing and pushing. Making a temporary commit also creates risk that I could accidentally push something unfinished and still broken.

**Comment by bendlas** [comment]
@takeda using `nixos-rebuild` together with `--override-input` works for me on

```console
% nix --version
nix (Nix) 2.24.10
```

what nix version are you on, and are you seeing an error from the flag, or does `nixos-rebuild` silently keep using the locked version?

**Comment by max06** [comment]
While I understand the reasoning behind... it's causing unnecessary issues.

For example: I'm currently working on `services.etcd`. For that I forked this repo, cloned my fork locally and made modifications. To test them interactively, I have to deploy these to my 3-node test cluster. My deployments run through colmena - there's no nixosConfiguration-output for those nodes.

How do I tell colmena to override the input? Do I have to comment out all inputs I use for such changes before I can deploy something else, like my local machine? Or even worse: Does colmena only work by accident this way since this should actually be an error instead of a warning?

**Comment by RooSoft** [comment]
Also, I am working on microVMs. So far, there is no way to use the `--override-input` flag with them, so I am forced to commit every single change despite most of them being garbage.

**Comment by max06** [comment]
The only solution I see right now: Duplicating my flake.nix into a development.nix. At least colmena allows me to choose the different flake.

**Comment by NiklasGollenstede** [comment]
I think there are two sides to this issue:
(1) it breaks a bunch of related but different workflows, with no _convenient_ alternatives, and
(2) whether to see unclean local git repos as lockable inputs.

To (1): This is a flake issue, flakes are officially "experimental", yet a significant portion of all things and people Nix rely on flakes. It would be nice if Nix remained usable as it was, unless there benefits that outweigh the pain that breaking changes cause.
In this case, I think most relevantly:
(a) not all tools allow you to pass through arbitrary nix options to all their calls to nix; some may even directly read the lock file (`flake-compat`?)
(b) even if possible, passing `--override-input` all the time can be quite inconvenient (and error-prone).

So, (2) on to the question whether (snapshots of) unclean git threes should be allowed as flake lock entries.

> Lock files should not contain unlocked entries [...], since that would defeat the whole point of a lock file.
-- @edolstra, [2024-12-06](https://github.com/NixOS/nix/issues/11181#issuecomment-2523867524)

That in itself I agree with. If the point of the lock file is to only proceed with inputs that precisely match those locked (and otherwise try to obtain them or fail), then the lock file should not be written when inputs can't be described precisely (and a command that is told wo write a lock file should fail if it doesn't).

Thing is, "dirty Git trees" (the omission in the quote above) are pinned with perfect precision in the lock file via their `narHash`. Nix will only ever proceed with that exact input, or it will fail. (`nix flake lock` puts it in the local store, but there are other ways how it could get there.)

So what do we gain by requiring local git repos to be clean? I guess the idea is that "if it is a commit, then we can download it on machines where the input is not in the store yet".
But that is flawed. There is neither a guarantee that a commit ever leaves the local machine (`git commit --amend`, never pushing, ...), nor that it can be downloaded where the input is missing (non-public repos, no internet, ...).
At the same time, the non-commit input may very well be present (same machine/store, `nix copy`, ...).
That means, with "clean" inputs, nix may still fail to obtain them, and with unclean inputs, it may still succeed.
(And "make sure dependencies are already there, cuz we won't be able to download them" is a quite nix pattern, no?)

That leaves the question: What do we gain for our pain here? Anything that a `grep -q '"dirtyRev"' flake.lock` wouldn't have done?

**Comment by max06** [comment]
Comparing this to `npm` or any other package manager: You can define dependencies and update your lockfile locally without ever committing them. That's convenient enough to do whatever you want during development on your machine, even putting dirty local dependencies in them. 

I, as the developer, have to decide when something is ready to be committed - this include the lockfile. I am responsible to make sure my lockfile matches my defined dependencies, and that my dependencies are actually also available on other systems where I intend to build or run my project.

I don't see why nix tries to know better than the developer working on things? Same goes for the "a file needs to be known by git"-approach. What's next? Nix forces me to commit everything before I can even test a change locally?

Don't force things. Hand out warnings about untracked files, dirty inputs if you want to, but don't try to know it better.

**Comment by Shados** [comment]
@edolstra
> So the solution is: don't use `nix flake lock` when you want to test against a dirty local repo; pass `--override-input` to `nix build` or `nixos-rebuild` instead.

If I pass `--override-input` to my `nix build`, and the input I'm overriding in turn has updated inputs/lockfile, this still uses the versions of the its dependencies from my top-level flake lock file. Is this behaviour a bug? If it is not, then the semantics of your solution are quite distinct to allowing locking dirty git inputs, and still forces users to rely on making unnecessary temporary commits.

**Comment by paumr** [comment]
Sadly this update also fully broke my workflow. 
To be able to use an uptodate version of nix/nixos I'm currently using this hack. 
NOTE: this is a hack. It serves as a workaround till I have time to plan, test and schedule all migrations.

<details>
<summary>show me the diry hack</summary>
Content of nix overlay:

``` nix
final: prev:
{
  nix = prev.nix.overrideAttrs (old: rec {
    # ignore unlocked inputs.
    # this was created as a temporary workaround:
    # https://github.com/NixOS/nix/issues/11181
    # this patch was tested with nix 2.24.10
    patches = [ 
      ../patches/hack_allow-local-inputs.patch
    ];
  });
}
```

Content of hack_allow-local-inputs.patch:
```
diff --git a/src/libexpr/primops/fetchTree.cc b/src/libexpr/primops/fetchTree.cc
index 0e49cbc71..c2db7c67a 100644
--- a/src/libexpr/primops/fetchTree.cc
+++ b/src/libexpr/primops/fetchTree.cc
@@ -174,17 +174,6 @@ static void fetchTree(
     if (!state.settings.pureEval && !input.isDirect() && experimentalFeatureSettings.isEnabled(Xp::Flakes))
         input = lookupInRegistries(state.store, input).first;
 
-    if (state.settings.pureEval && !input.isLocked()) {
-        auto fetcher = "fetchTree";
-        if (params.isFetchGit)
-            fetcher = "fetchGit";
-
-        state.error<EvalError>(
-            "in pure evaluation mode, '%s' will not fetch unlocked input '%s'",
-            fetcher, input.to_string()
-        ).atPos(pos).debugThrow();
-    }
-
     state.checkURI(input.toURLString());
 
     auto [storePath, input2] = input.fetchToStore(state.store);
diff --git a/src/libflake/flake/flake.cc b/src/libflake/flake/flake.cc
index 627dfe830..45517c441 100644
--- a/src/libflake/flake/flake.cc
+++ b/src/libflake/flake/flake.cc
@@ -663,10 +663,6 @@ LockedFlake lockFlake(
 
             if (lockFlags.writeLockFile) {
                 if (sourcePath || lockFlags.outputLockFilePath) {
-                    if (auto unlockedInput = newLockFile.isUnlocked()) {
-                        if (state.fetchSettings.warnDirty)
-                            warn("will not write lock file of flake '%s' because it has an unlocked input ('%s')", topRef, *unlockedInput);
-                    } else {
                         if (!lockFlags.updateLockFile)
                             throw Error("flake '%s' requires lock file changes but they're not allowed due to '--no-update-lock-file'", topRef);
 
@@ -723,7 +719,6 @@ LockedFlake lockFlake(
                             flake.lockedRef.input.getRev() &&
                             prevLockedRef.input.getRev() != flake.lockedRef.input.getRev())
                             warn("committed new revision '%s'", flake.lockedRef.input.getRev()->gitRev());
-                    }
                 } else
                     throw Error("cannot write modified lock file of flake '%s' (use '--no-write-lock-file' to ignore)", topRef);
             } else {
diff --git a/src/libflake/flake/lockfile.cc b/src/libflake/flake/lockfile.cc
index 80f14ff6f..3d1b319a2 100644
--- a/src/libflake/flake/lockfile.cc
+++ b/src/libflake/flake/lockfile.cc
@@ -43,9 +43,6 @@ LockedNode::LockedNode(
     , originalRef(getFlakeRef(fetchSettings, json, "original", nullptr))
     , isFlake(json.find("flake") != json.end() ? (bool) json["flake"] : true)
 {
-    if (!lockedRef.input.isLocked())
-        throw Error("lock file contains unlocked input '%s'",
-            fetchers::attrsToJSON(lockedRef.input.toAttrs()));
 }
 
 StorePath LockedNode::computeStorePath(Store & store) const
diff --git a/tests/functional/fetchGit.sh b/tests/functional/fetchGit.sh
index 78925b5cd..3ec3443ff 100755
--- a/tests/functional/fetchGit.sh
+++ b/tests/functional/fetchGit.sh
@@ -69,8 +69,6 @@ nix eval --impure --raw --expr "builtins.fetchGit { url = file://$repo; rev = \"
 [[ $(nix eval --raw --expr "builtins.readFile (builtins.fetchGit { url = file://$repo; rev = \"$devrev\"; allRefs = true; } + \"/differentbranch\")") = 'different file' ]]
 
 # In pure eval mode, fetchGit without a revision should fail.
-[[ $(nix eval --impure --raw --expr "builtins.readFile (fetchGit file://$repo + \"/hello\")") = world ]]
-(! nix eval --raw --expr "builtins.readFile (fetchGit file://$repo + \"/hello\")")
 
 # Fetch using an explicit revision hash.
 path2=$(nix eval --raw --expr "(builtins.fetchGit { url = file://$repo; rev = \"$rev2\"; }).outPath")
@@ -79,9 +77,6 @@ path2=$(nix eval --raw --expr "(builtins.fetchGit { url = file://$repo; rev = \"
 # In pure eval mode, fetchGit with a revision should succeed.
 [[ $(nix eval --raw --expr "builtins.readFile (fetchGit { url = file://$repo; rev = \"$rev2\"; } + \"/hello\")") = world ]]
 
-# But without a hash, it fails
-expectStderr 1 nix eval --expr 'builtins.fetchGit "file:///foo"' | grepQuiet "'fetchGit' will not fetch unlocked input"
-
 # Fetch again. This should be cached.
 mv $repo ${repo}-tmp
 path2=$(nix eval --impure --raw --expr "(builtins.fetchGit file://$repo).outPath")
@@ -221,7 +216,6 @@ path6=$(nix eval --impure --raw --expr "(builtins.fetchTree { type = \"git\"; ur
 [[ $path3 = $path6 ]]
 [[ $(nix eval --impure --expr "(builtins.fetchTree { type = \"git\"; url = \"file://$TEST_ROOT/shallow\"; ref = \"dev\"; shallow = true; }).revCount or 123") == 123 ]]
 
-expectStderr 1 nix eval --expr 'builtins.fetchTree { type = "git"; url = "file:///foo"; }' | grepQuiet "'fetchTree' will not fetch unlocked input"
 
 # Explicit ref = "HEAD" should work, and produce the same outPath as without ref
 path7=$(nix eval --impure --raw --expr "(builtins.fetchGit { url = \"file://$repo\"; ref = \"HEAD\"; }).outPath")
```
</details>

**Comment by megheaiulian** [comment]
This does not look like good developer experience. 
Perhaps there should be simple file:// (not "git+file") input type that works just like a link.

**Comment by edolstra** [comment]
This is fixed by #12220.
