### ISSUE TITLE
Support for networks that only allow HTTP/HTTPS

### ISSUE THREAD

**Issue by catern** [NixOS/nix#1403]
I am trying to spin up Nix on servers at my work. But:

1. I don't have root, so I can't put the store in /nix/store, and
2. My network out is firewalled such that the server can only download HTTP/HTTPS sources.

Problem 1 means that I can't use binary substitutes, but problem 2 means that I often running into problems compiling from source. There are a fair number of packages in nixpkgs which download sources over FTP or git, and so I have been just manually prefetching those for now - not a good solution.

One way to fix this that might be generally applicable, is to allow downloading substitute sources from the cache server, even if its StoreDir is not compatible. (Not sure if Hydra even saves sources in the first place right now?)

I think there are a fair number of people who have to work behind these aggressive corporate firewalls, so supporting this seems useful.

Thanks for Nix!

**Comment by Ekleog** [comment]
I'd even think all fixed-output derivations should be possible to download from hydra (if cache.nixos.org does store it) even if the architecture or whatever mismatches: anyway, the output is fixed, so whatever the parameters are if nix reaches the point where it should build it, it could as well be downloaded from any cache.

Then, I guess it requires potentially substantial changes in the handling of binary caches by nix, but it may be worth it (I have a friend with a similar issue, an armv7l board behind a restrictive firewall, he disabled sudo to not be bothered by the ftp download if I remember correctly)

Also, it puts more pressure on the cache servers, then I didn't pay attention to whether normal source downloads (/nix/store and x86_64) go through the cache or directly from upstream, but it may be a dealbreaker if it doesn't at the moment.

**Comment by vcunat** [comment]
@catern: I'd recommend you to try proot.  There've been some threads about the usage around https://github.com/NixOS and the mailing-list.  It should allow you to use the binary cache without being root with a small runtime penalty, assuming you run a new enough kernel IIRC.

**Comment by edolstra** [comment]
Nix 1.12 has proot-like functionality built-in, e.g.
```
nix build --store local?root=/tmp/nix nixpkgs.hello
```
will install Hello into a chroot at /tmp/nix.

**Comment by catern** [comment]
OK, so proot solves the problem of not being able to put the store at /nix/store.

But I still can't download sources over FTP or the git protocol. I think it would still be useful to solve that?

**Comment by copumpkin** [comment]
I've often wondered if it would make sense for cache.nixos.org to cache fixed-output inputs into our builds, perhaps under some size threshold. They're generally not very big and it gives us a reproducibility improvement too, since occasionally upstream sources will disappear or modify files in place, leaving us wondering what changed. Of course, I'm not paying for the S3 bucket...

**Comment by edolstra** [comment]
@copumpkin That's already the case.

**Comment by copumpkin** [comment]
@edolstra oh awesome! So you already cache all FO derivation inputs? Curious why that doesn't address all of @catern's issues then.

**Comment by edolstra** [comment]
Yes, but they're only usable if you use `/nix/store` as your store location.

**Comment by vcunat** [comment]
Does the hash before name in fixed-output derivations depends on nix store location?  If so, why should it be so?

EDIT: well, considering that there are ways to avoid the prefix change, it's probably not important to improve this...

**Comment by edolstra** [comment]
Yes, IIRC, the hash depends on the store location. I don't remember why - maybe for future compatibility with the intensional (content-addressed) model where such paths could have references.

**Comment by zimbatm** [comment]
This can be closed since nix 2.0 implements the `--store` feature

**Comment by catern** [comment]
I don't believe this should actually be closed: as mentioned before, you can't use fixed-output derivations from cache.nixos.org if you aren't using /nix/store.

Perhaps the name of the issue should be changed, but allowing the use of FO substitutes from c.n.o while using a store location other than /nix/store still seems like a good thing to dod.

**Comment by fricklerhandwerk** [comment]
@catern Thanks for picking it up. Please rename the issue to be more self-descriptive. :)

**Comment by catern** [comment]
So, just to summarize again: the issue is that fixed-output derivations (e.g. tarballs, source code, etc) don't actually depend on the store location (e.g. /nix/store, /guix/store, /home/catern/store, etc), so there's nothing stopping a store at location A from using fixed-output derivations which were built in a store at location B.

Except that Nix currently doesn't allow/support that, because the derivation hash depends on the store location.
