### ISSUE TITLE
Suggestion: per-user profiles should use uid, not username

### ISSUE THREAD

**Issue by lilyball** [NixOS/nix#2757]
Why does Nix store per-user profiles under username instead of uid? Usernames can change.

**Comment by edolstra** [comment]
Well, uids can also change...

The real issue here is that Nix should store per-user profiles in the user's home directory.

**Comment by lilyball** [comment]
I mean, uids could technically change, but it would screw up a lot of stuff to do that (e.g. all of the user's files are suddenly no longer owned by that user). Meanwhile, I actually *want* to change my local username, and software like Nix that rely on the username instead of the uid makes me worried about the implications of doing this.

**Comment by lilyball** [comment]
I went ahead and changed my username today, and AFAICT Nix was the only software on my computer that was relying on my old username. I updated that manually, and everything else seems to just work.

**Comment by bjornfor** [comment]
Using user name instead of uid also cause problems on non-nixos setups with LDAP/SSSD, because the nix-daemon is unable to get the user name and thus nix-env and the daemon disagree on where the user profile is.

**Comment by r-burns** [comment]
@bjornfor I think I have run into the same issue - on a machine using LDAP+SSSD, the nix daemon creates /nix/var/nix/profiles/per-user/12345 for me, but the nix commands create ~/.nix-profile as a broken symlink to /nix/var/nix/profiles/per-user/r-burns/profile (which does not exist) and `nix-env -i` commands error with

```
error: opening lock file '/nix/var/nix/profiles/per-user/r-burns/profile.lock': No such file or directory
```
Is this what you were referencing here https://github.com/NixOS/nix/issues/4565?

**Comment by bjornfor** [comment]
> Is this what you were referencing here #4565?

Yes.

**Comment by sgraf812** [comment]
Same here as 2 comments up: Nix multi-user install on Ubuntu.

**Comment by Ericson2314** [comment]
@edolstra  said above

> The real issue here is that Nix should store per-user profiles in the user's home directory.

Would this solve the LDAP problem? That does sound like the right thing to me.

It does mean per-machine GC roots for shared, perhaps mounted-on-demand user home directories wouldn't work, but that seems like the correct behavior honestly.

**Comment by HaoZeke** [comment]
Thanks for the the mention @Ericson2314. I don't think having the profiles stored on home directories is a good idea for cluster installations.

**Comment by benley** [comment]
> Using user name instead of uid also cause problems on non-nixos setups with LDAP/SSSD, because the nix-daemon is unable to get the user name and thus nix-env and the daemon disagree on where the user profile is.

Is there a known workaround for this issue?  I'd like to use multi-user nix on systems with LDAP+SSD users and I keep getting stuck here.

**Comment by r-burns** [comment]
@benley Yes, you need to manually fix the broken ~/.nix-profile symlink. Assuming it's currently pointing to the incorrect username-based location, change it to point to the UID-based location.

Bad:

```
  File: ‘/home/r-burns/.nix-profile’ -> ‘/nix/var/nix/profiles/per-user/r-burns/profile’
```

Good:

```
  File: ‘/home/r-burns/.nix-profile’ -> ‘/nix/var/nix/profiles/per-user/12345/profile’
```

**Comment by benley** [comment]
Oh nice, thank you!  That is much simpler than what I was about to do, which was putting the profile in my homedir:

```sh
mkdir -p ~/._nix_profiles
nix-env -S ~/._nix_profiles/$USER
```

I think you can fix the symlink using nix-env as well, for what it's worth:

```sh
nix-env -S /nix/var/nix/profiles/per-user/12345/profile
```

**Comment by bjornfor** [comment]
Another workaround is setting LD_LIBRARY_PATH  to include ldap and sss library paths in the nix-daemon systemd service file (preferably an override file to not mess with the one provided by nix itself).

**Comment by mtalexan** [comment]
I would recommend re-classifying this as a bug rather than a suggestion.  

As per #4565 mentioned previously, systems that use SSO/LDAP PAM but have a multi-user install fail with a non-obvious error due to a mismatch between the code creating the profile folder at `/nix/var/nix/profiles/<UID>/profiles` and the code creating the `.nix-profile` symlink in the home directory (points to `/nix/var/nix/profiles/<UNAME>/profiles`).  

The easy solution here seem to be to just always use the UID rather than trying to use the UNAME that can only be resolved in some conditions.

**Comment by mtalexan** [comment]
Maybe this isn't actually the answer either.  I just discovered the Home-manager separately suffers from the same problem in `/nix/var/nix/gcroots/per-user/$USER`.

If this change were to happen, the Home-Manager tool would also need to be updated to look for the UID instead of the UNAME.  There could also be any number of other tools that would also need to be updated (I'm not familiar enough with the full community set of tools to know).

**Comment by bjornfor** [comment]
Not stale. (I wish I didn't have to write this comment, but I think the Nix Stale bot still *closes* stale issues, and I don't want that.)

**Comment by polygon** [comment]
This is STILL an issue and it's a freaking BIG one. I swear, if Nix adaptation in our company fails, it is because difficult to explain issues like these are literally the first impression that people get when installing Nix in a SSSD/LDAP environment - weird error messages and nothing working.

It's even reproducible. Delete the `.nix-profile`-symlink in the home-directory and the profile under `/nix/var/nix/profiles/per-user`, logout and login again, then do something related to the user profile. You will get a directory `/nix/var/nix/profiles/per-user/$UID` but a broken `.nix-profile` symlink pointing to `/nix/var/nix/profiles/per-user/$USER`.

Possibly modifying the systemd-unit for `nix-daemon` would be an option, but of course, it points (and itself lives) inside the Nix-store, so you cannot just simply modify it. So we would need an overlay for this, but since this is not a NixOS system, that probably means maintaining a patched version of nixpkgs? I wouldn't even know how to apply overlays to the `nix-daemon` package when installed in a Non-NixOS system. Can we please fix this once and for all? It is quite embarrassing.

**Comment by Ericson2314** [comment]
Nix 2.14 (released but currently quasi-revoked until somethings are fixed), moves the profiles inside home directories, side-stepping this issue.

Assigned to @thufschmitt to either close right away or close once the 2.14 (or newer) is once again the default installer.

**Comment by thufschmitt** [comment]
Closing since https://github.com/NixOS/nix/pull/5226 got rid of this `per-user` profiles thing altogether. Feel free to reopen if there's still something missing
