### ISSUE TITLE
.nix-profile symlink broken

### ISSUE THREAD

**Issue by haribole** [NixOS/nix#4565]
I installed nixOS but after the installation the symlink to ~/.nix-profile is broken:

.nix-profile -> /nix/var/nix/profiles/per-user/smx/profile

The target file does not exist.

am I missing a step in the installation?

**Comment by bjornfor** [comment]
Is your user a local user, or one defined in LDAP/SSSD?

Is this a multi-user install?

**Comment by haribole** [comment]
local user, multi-user install 

Thanks!

**Comment by haribole** [comment]
I was able to generate the profile, but now the /home/smx/nixpkgs.nix is missing

Apologize if this is a newbie issue. Still in the process of going through the documentation and wrapping my mind around nix :)

**Comment by bjornfor** [comment]
> I was able to generate the profile, but now the /home/smx/nixpkgs.nix is missing

Nix doesn't install that file. (Perhaps you meant another path?)

> Apologize if this is a newbie issue. Still in the process of going through the documentation and wrapping my mind around nix :)

:-)

I'm not a core Nix contributor, but you might want to try https://discourse.nixos.org/ or IRC for general help. (I just wanted to check if your issue was related to LDAP users.)

**Comment by mtalexan** [comment]
Bump.

The issue is still very much open.  Multi-user installs on systems with federated credentials (LDAP/SSO/SSSD) always end up with a broken symlink in the home folder.  

According to #2757 this is because the nix-daemon is unable to get the UNAME of the user and falls back to the UID when creating the `/nix/var/nix/profiles/$USER` subfolder, but the installer creating the symlink in the user's home folder is able to resolve it to a UNAME.

If someone can point me to where the https://nixos.org/nix/install script code is hosted, I'd gladly submit a simple PR that determines whether the user's profile folder in `/nix/var/nix/profiles/$USER` uses UID or UNAME and generates the symlink accordingly.

**Comment by mtalexan** [comment]
It turns out this problem is more wide-spread, and affects a number of other tools as well.  Attempting to install Home-Manager fails even after the `.nix-profile` is fixed because the `/nix/var/nix/gcroots/per-user/$USER` suffers from the same problem.

Maybe the installer script needs to elevate to sudo to create symlinks at the UNAME to point to the UID folders in the `/nix/var/nix/{gcroots,profiles}/per-user/$USER` instead so either can be used on multi-user installs.  Doing so manually seems to have solved the problem for me so far.

**Comment by mtalexan** [comment]
Bump again, still not addressed, even with the recent nix release.

**Comment by mkatychev** [comment]
@mtalexan  can you post the commands you ran to fix this issue?

**Comment by mtalexan** [comment]
If you're using the "experimental" `nix-commands` option, you should be using `nix profile` instead of `nix-env`. The `nix profile` no longer (seems) to rely on the symlink in your home folder anymore. However it still breaks on the `/nix/var/nix/profiles/per-user/` subfolder being missing for your username under certain conditions, and that will also break the symlink.

I ran this command that seems to fix both cases (be aware you can't use both `nix profile` and `nix-env`, whichever you use first after install is the only one you can use)
```
sudo ln -srf /nix/var/nix/profiles/per-user/$(id -u) /nix/var/nix/profiles/per-user/$(id -u)
```

**Comment by slenderq** [comment]
New user, Also having the same problem. All new nix installs with the recommended multi-user setup were failing for me. 
Ended up just doing a single user install just to get it working. 

This was really confusing to figure out! This is the only thread I could find that provided me with the solution.

**Comment by Ericson2314** [comment]
@mtalexan

> If someone can point me to where the https://nixos.org/nix/install script code is hosted, I'd gladly submit a simple PR that determines whether the user's profile folder in /nix/var/nix/profiles/per-user/$USER uses UID or UNAME and generates the symlink accordingly.

if you want to tackle this issue, that would be much appreciated!

The default installer lives in this repo: `scripts/install.in`.

**Comment by mtalexan** [comment]
It appears the `scripts/install.in` is just doing the `curl` or `wget` download of the latest release package, and runs the installer out of that release package.  I can update the install script for some of the targets that get installed.

However the experimental `commands` configuration no longer seems to use the `~/.nix-profile` symlink for the replacement `nix profile` command (it did use to, but doesn't anymore), and requires a symlink in the destination location rather than in the home folder. See https://github.com/NixOS/nix/issues/4565#issuecomment-1367661952.  

There's also apparently some impetus around re-implementation of the entire installer (https://determinate.systems/posts/determinate-nix-installer).  While that's obviously not official yet, it does beg the question of how much should be invested in the current installer in support of the legacy (but still default) `nix-env` profile commands.

**Comment by mtalexan** [comment]
> It appears the scripts/install.in is just doing the curl or wget download of the latest release package, and runs the installer out of that release package. I can update the install script for some of the targets that get installed.

Actually, the `nix-env` has also been modified to no longer use the `~/.nix-profile` symlink either (See lines 11-29 https://github.com/NixOS/nix/blob/master/scripts/nix-profile.sh.in#L11).  Profiles are now stored in `~/.local/state/nix/profile` (or `$XDG_STATE_HOME/nix/profile` if set) and don't need symlinks to them anymore.  

So this bug only applies if you're installing a version of nix that still uses the legacy `~/.nix-profile` symlink, and any fix could only be distributed in new versions of nix (which don't use the `~/.nix-profile` symlink).  

The solution to this seems to be to install a newer version of Nix, or manually fix the legacy issue following my previous directions: https://github.com/NixOS/nix/issues/4565#issuecomment-1367661952

**Comment by mtalexan** [comment]
@Ericson2314   
Can we close this issue with the summary solution options:
- Install a newer version of Nix, the `~/.nix-profile` is no longer used and the new solution doesn't have the same problem.  

or

- Manually fix the issue in the legacy installer with the command:
```
sudo ln -srf /nix/var/nix/profiles/per-user/$(id -u) /nix/var/nix/profiles/per-user/$(id -un)
```

**Comment by Ericson2314** [comment]
@mtalexan well note that 2.14 had many issues and so we've temporarily made 2.13 the default installer. Out of an abundance of caution, I think this should be kept open lest 2.13 have the issue still.

**Comment by mtalexan** [comment]
Good to know. It unfortunately doesn't change the fact that an installer fix has to be shipped with an updated installer, so it's manual or nothing for any prior installer release, but I understand leaving it open.

**Comment by Ericson2314** [comment]
@mtalexan But do you know how to fix Nix 2.13? We can still accept PRs to a release branch? I think that would be prudent if the fix is low risk, since it is unclear how long we will be stuck on 2.13.

**Comment by mtalexan** [comment]
I've looked into it pretty extensively, and it's not an easy fix. It requires bloated error checking logic with likely significant performance penalties in most of the tool run-times since it can't be fixed at install time.

It turns out the `~/.nix-profile` symlink is just created during installation to point to the default root profile, and then on first use is corrected by the run-time to point to the per-user profile based on username.  The problem is that the Linux system call itself returns different values for the "username" string of a non-local (e.g. LDAP) user based on some difference in calling context between install-time and run-time.  At install time the "username" is reported as a stringified version of the UID, but at run-time it's reported as the actual username.  This results in installation using the UID-named per-user location, while all of the run-time tools have their own hardcoded logic to build and use the username per-user path.  

The least invasive solution would be to always use stringified UIDs for the per-user path, both at install-time and at run-time.  But for backwards compatibility with existing installs we'd have to check the path existence and fallback to the username per-user folder name.  Most of the 2.13 run-time code doesn't even check the paths that are built, it just relies on them being present and propagates exceptions pretty far up the call-tree if the assumptions ends up being wrong.  All of these locations would have to add existence checks to determine which path to use, which is going to incur some performance penalties.    
I'm guessing we also don't want to put in such an extensive 2.13-post-release change when there's already a rework of the entire profile system in the 2.14 release.  I can put together a basic MR if you want to see specifically what I'm talking about.

**Comment by Ericson2314** [comment]
@mtalexan Thanks again for that extensive investigation. I really appreciate it.

So basically, this is more of #2757 and #3356 type stuff, right?

> I'm guessing we also don't want to put in such an extensive 2.13-post-release change when there's already a rework of the entire profile system in the 2.14 release

Yes, now that I understand what is going in, I think that is the case. As you say, there isn't really a natural backwards compatible "fix" on this --- it would be complicated logic special-casing based on the current state it sounds like.

The currently plan (as I understand it) is also to not try to make the new profile locations more backwards compatible (which doesn't seem possible without lots of pain), but just fix the bugs and continue ripping off the band-aid. So I think this is in keeping with that too.

I will assign these 3 issues to @thufschmitt to either close right away, or close once we are back to having 2.14 (or newer) as the default installer.

**Comment by mtalexan** [comment]
> So basically, this is more of #2757 and #3356 type stuff, right?

That's where the fix would lie, yes.  

There's probably other possibilities, but as mentioned in #2757 the core problem is that the installer doesn't know what the username is, and has no reliable way to figure it out for the use cases experiencing this problem.

**Comment by thufschmitt** [comment]
Closing since (as far as I understood), Nix 2.14+ don't have this problem any more. Feel free to complain if that's not the case

**Comment by RobbieMcKinstry** [comment]
Ah, I'm sorry to report this, but I believe Nix 2.14+ does indeed still have this problem.
Today, I opened up a brand new Apple Mac, installed Nix before anything else, and soon thereafter came across this bug.

I'm using Nix-Darwin and Home-Manager to install my dev tools. I downloaded my repository with my Nix config in it, and ran the following:

```bash
$ nix build ".#" --extra-experimental-features "nix-command flakes"
$ ./result/sw/bin/darwin-rebuild switch --flake ".#robbie"
```

Now, I see that the Nix-profile link is broken:

```bash
$ ls -la ~
# This line is most important.
lrwxr-xr-x@  1 robbie  staff     45 Jun 28 20:55 .nix-profile -> /nix/var/nix/profiles/per-user/robbie/profile
# Omitting unrelated lines, but these are potentially relevant. 
lrwxr-xr-x@  1 robbie  staff     71 Jun 28 21:52 .profile -> /nix/store/smm3rsvc3r79m88ymn0yrykvc1b07az4-home-manager-files/.profile
lrwxr-xr-x@  1 robbie  staff     76 Jun 28 21:52 .bash_profile -> /nix/store/smm3rsvc3r79m88ymn0yrykvc1b07az4-home-manager-files/.bash_profile
lrwxr-xr-x@  1 robbie  staff     70 Jun 28 21:52 .bashrc -> /nix/store/smm3rsvc3r79m88ymn0yrykvc1b07az4-home-manager-files/.bashrc
lrwxr-xr-x@  1 robbie  staff     71 Jun 28 21:52 .manpath -> /nix/store/smm3rsvc3r79m88ymn0yrykvc1b07az4-home-manager-files/.manpath
drwxr-xr-x@  4 robbie  staff    128 Jun 28 21:20 .nix-defexpr

$ ls /nix/var/nix/profiles/per-user/robbie/
home-manager
home-manager-1-link
home-manager-2-link
```

From this, I was able to conclude that _almost_ everything worked. The other links are all valid store locations, and if I edit my nix-darwin config to _e.g._ install the Fish shell, I see that reflected on my system. My other Home Manager programs are installed too.

However, they're not available in PATH, because my PATH expects `~/.nix-profile/bin` to exist:

```bash
$ echo $PATH
/Users/robbie/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

As a result, none of my installed Home Manager binaries are available on my system.

--------
## Additional Information:

* **My machine:** 2023 M2 Mac Pro.

* **Nix Version and Installation mode**

```bash
$ nix --version
nix (Nix) 2.16.1
# Installation Script: Multi-user MacOS install
$ sh <(curl -L https://nixos.org/nix/install)
```

* My `flake.nix` file, which might not be relevant:

```nix
{
  description = "This flake standardizes my dev environment across machines.";
  inputs = {
    nixpkgs.url = "flake:nixpkgs/nixpkgs-unstable";
    darwin.url = "flake:nix-darwin";
    darwin.inputs.nixpkgs.follows = "nixpkgs";
    home-manager.url = "flake:home-manager";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";
    flake-utils.url = "github:numtide/flake-utils";
  };
  outputs = { self, nixpkgs, darwin, home-manager, flake-utils, ... }@inputs:
    let 
      # Grab the file containing the home-manager module.
      homeModule = ./home/default.nix;
      # Grab the file containing the nix-darwin module.
      darwinModule = ./darwin/default.nix;
      homeArgs = {
        home-manager.useUserPackages = true;
        home-manager.users.robbie = import homeModule;
      };
      # Create the Darwin Modules by composing Home Manager modules
      # into a Nix-Darwin mod.
      mods = [
          darwinModule
          # Curry the creation of this home-manager mod with the args.
          home-manager.darwinModules.home-manager
          homeArgs
      ];
    in
    rec {
      darwinConfigurations."robbiemckinstry" = darwin.lib.darwinSystem {
        system = "x86_64-darwin";
        inputs = { inherit darwin nixpkgs; };
        modules = mods;
      };

      # We use a separate import for the separate architecture.
      # Ultimately we should switch to flakeutils for this!
      darwinConfigurations."robbie" = darwin.lib.darwinSystem {
        system = "aarch64-darwin";
        inputs = { inherit darwin nixpkgs; };
        modules = mods;
      };

      # This allows us to build with .# instead of .#darwinConfigurations...
      defaultPackage.x86_64-darwin = darwinConfigurations."robbiemckinstry".system;
      defaultPackage.aarch64-darwin = darwinConfigurations."robbie".system;
    };
}
```

Not including the rest of my config to keep the signal to noise ratio of this comment reasonable.

**Comment by GeekOfTheWild** [comment]
I think this might be related: I did an install of NixOS recently (Calamares) and whenever I try to use nix-env to install a package or setup home-manager, I get this error:
error: '/home/geekofthewild/.nix-profile' is not a symlink
Anyone know what this is? Is it related or its own problem, or did I just do something wrong?

**Comment by GeekOfTheWild** [comment]
Yes, it is 2.13.5

**Comment by OctoRocket** [comment]
I'm getting this issue on Nix 2.17.1
![image](https://github.com/NixOS/nix/assets/88291550/258c939f-11ab-4a60-b007-dc5a3f5f4ccf)

**Comment by thufschmitt** [comment]
> I'm getting this issue on Nix 2.17.1 ![image](https://user-images.githubusercontent.com/88291550/285064156-258c939f-11ab-4a60-b007-dc5a3f5f4ccf.png)

I'm not sure what's causing it (any special thing you did before reaching that state?), but a few things worth trying:

- Did you already run a `nix-env` or `nix profile` command? If no, try that first. I don't remember for sure, but it might be that the `.nix-profile` symlink is created eagerly while the actual profiles are only created once there's something to install
- Otherwise, try removing `~/.nix-profile` and let Nix re-create it

**Comment by peterbecich** [comment]
Slight different error
```
error: creating symlink from '/home/peterbecich/haskell/halogen_chess/result.tmp-3901647-849012186' 
  to '/nix/store/kw1805rc7iiw3v08nwkx9xx17dkrs9iq-docker-image-halogen-chess.tar.gz': Permission denied
```

I solved this by
```
rm -rf ~/.cache/nix
```

**Comment by Ashvith10** [comment]
This issue still persists on Nix 2.16.1. I'm on a Guix System, btw. Although flake seems to be working fine, but most the apps do not launch properly on CLI, for example, Setzer. None of the LaTeX editor also seem to be working properly.

**Comment by NovaViper** [comment]
🤔 This seems to be broken still even on nix 2.18.2; but oddly only on ISO images. I create my ISO image [based on my flake config](https://github.com/NovaViper/NixConfig/blob/main/hosts/live-image/default.nix) and the link for .nix-profile is broken; and it looks like it started doing this since I switched to the upstream nix version (`github:nixos/nix/2.22-maintenance`).
