### ISSUE TITLE
"experimental feature 'ca-derivations' is disabled" even though it is enabled

### ISSUE THREAD

**Issue by NobbZ** [NixOS/nix#4784]
**Describe the bug**

I wanted to try to rebuild the system in question using the new content addressable features, therefore I updated it to a recent stable release.

Whenever I try to build a CA enabled system config on that machine I get the following error:

```plain
$ nix build .\#nixosConfigurations.delly-nixos.config.system.build.toplevel
error: experimental Nix feature 'ca-derivations' is disabled; use '--experimental-features ca-derivations' to override
(use '--show-trace' to show detailed location information)
```

The error does *not* change, even if I provide `--experimental-features 'ca-derivations flakes nix-command'` on the CLI explicitely.

Also it is set in the `nix.conf`:

```plain
$ cat /etc/nix/nix.conf| grep experi
experimental-features = nix-command flakes ca-derivations ca-references
```

Building any CA enabled system config on one of my other systems works fine.

**Steps To Reproduce**

1. Try to build any system with `nixpkgs.config.contentAddressedByDefault = true;` on the affected system.
2. See it fail as described above

**Expected behavior**

A system configuration is built.

**`nix-env --version` output**

```text
$ nix-env --version
nix-env (Nix) 2.4pre20210504_fe3a10a
```

**Additional context**

The system where the problem occurs is quite an old machine with an Intel Core2Duo CPU and only 4 GiB of RAM, though I wouldn't expect this to cause the actual error.

In general the configuration of my systems is available at https://github.com/NobbZ/nixos-config

The most relevant file for the affected system is probably https://github.com/NobbZ/nixos-config/blob/master/nixos/hosts/legacy/delly-nixos.nix

If any further details about this system or any other in my setup are required just ask.

Please be aware that I won't have physical access to the affected machine for the next couple of days, only SSH until VPN or WiFi decides to crash.

**Comment by asymmetric** [comment]
@NobbZ is there something relevant in your `~/.config/nix/nix.conf`?

**Comment by NobbZ** [comment]
@asymmetric I do not have such a file.

**Comment by teto** [comment]
I've just rebased on nixos-unstable and experiments something similar:
```
$ sudo nixos-rebuild --flake ~/home --no-write-lock-file --override-input nixpkgs-teto /home/teto/nixpkgs --override-input hm /home/teto/hm

building the system configuration...
error: experimental Nix feature 'flakes' is disabled; use '--experimental-features flakes' to override
error: getting status of '/tmp/nixos-rebuild.PjbHJF/result': No such file or directory
```
with ~/.config/nix/nix.conf
`experimental-features = nix-command flakes`

It used to work fine, I haven't changed anything relevant, I ran two `switch` in a row, first one succeeded, second failed with the previous error.

**Comment by teto** [comment]
even stranger
```
 nix show-config | grep experimental                                                                                                                                                 ~/nixpkgsexperimental-features = nix-command flakes
 ```

**Comment by teto** [comment]
(for anyone hitting this, I was able to work around it with https://discourse.nixos.org/t/how-to-do-a-flake-build-in-non-nixos-system/10450/7)

**Comment by regnat** [comment]
> (for anyone hitting this, I was able to work around it with https://discourse.nixos.org/t/how-to-do-a-flake-build-in-non-nixos-system/10450/7)

Duuuuh, that explains everything! So what happens is that `nixos-rebuild --flake` sets `--experimental-features` ([here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/nixos-rebuild/nixos-rebuild.sh#L108)), overriding whatever’s in the config file.

https://github.com/NixOS/nixpkgs/pull/123246 should fix it

**Comment by NobbZ** [comment]
I did not use `nixos-rebuild` but directly build the corresponding attribute. The merged fix does not solve the reported problem. Can someone please re-open?

**Comment by regnat** [comment]
> I did not use nixos-rebuild but directly build the corresponding attribute

Duh, I knew I’d missed something :man_facepalming:

**Comment by regnat** [comment]
@NobbZ do you also have the error if you run `nix build` as root to bypass the Nix daemon?

**Comment by NobbZ** [comment]
Yes, I have, and I also have to add that the error happens for any `__contentAddressed = true` derivation that I try to build, not only system configuration.

**Comment by teto** [comment]
I also still have the issue with 
`error: experimental Nix feature 'flakes' is disabled; use '--experimental-features flakes' to override` with 2.4pre20210601_5985b8b even though flakes are enabled
```
nix show-config|grep flake                                                                                                                                                       
experimental-features = nix-command flakes
flake-registry = https://github.com/NixOS/flake-registry/raw/master/flake-registry.json
```

**Comment by asymmetric** [comment]
> BTW here is an undocumented feature - you can pass --option experimental-features "nix-command flakes" to nixos-rebuild

TBF, the `nixos-manpage` doe say

>        In addition, nixos-rebuild accepts various Nix-related flags, including --max-jobs / -j,
>        --show-trace, --keep-failed, --keep-going, --impure, and --verbose / -v. See the Nix manual for
>        details.

Wether this si sufficient as (indirect) documentaion though, I'm not so sure :)

**Comment by kanashimia** [comment]
> Wether this si sufficient as (indirect) documentaion though, I'm not so sure :)

Note that `nixos-rebuild` only supports _some_ very specific options of `nix`, basically the only way to know is by reading the source code.

**Comment by PopCat19** [comment]
For NixOS users, make sure `[/root|$HOME]/.config/nix/nix.conf` is removed if you are configuring nix through configuration.nix or nix flakes.

For non-NixOS users, check configurations in `.config/nix/nix.conf` and be sure it's set correctly. Remove if you're not setting any overrides.

I encountered this and found out I had `/root/.config/nix/nix.conf` with only `nix-command flakes`. It overrode the full system config at `/etc/nix/nix.conf`, even if it's regenerated. 

After removing `/root/.config/nix/nix.conf`, I restarted the nix daemon and now it's using the config from `/etc/nix/nix.conf` which included `ca-derivations`.

I'm not really sure why root's `/root/.config/nix/nix.conf` exists in presence of `/etc/nix/nix.conf`. I think it should be changed unless there's a reason.
