### ISSUE TITLE
`flake.lock` is forcefully added to git after changes

### ISSUE THREAD

**Issue by ncfavier** [NixOS/nix#5810]
**Describe the bug**

I have `flake.lock` in my `.gitignore` because I don't want to commit the lock file. Whenever I run a command that updates the lock file, it gets forcefully added to the files tracked by git:

https://github.com/NixOS/nix/blob/de273bbff2722c8abd134ddffd69e457a3938056/src/libfetchers/git.cc#L154-L155

**Expected behavior**

Don't do that. Why was `--force` added in the first place?

**Comment by armeenm** [comment]
> Don't do that. Why was --force added in the first place?

Went through some blames...
https://github.com/NixOS/nix/commit/d5334c466b9ee237a1cce4fd005d790e67d74822#diff-d4441d6156ea52c005e1517d6da41bdf989cff029b61d5f3e9f662a51861f5f2L591

> // Hack: Make sure that flake.lock is visible to Git, so it ends up in the Nix store.

**Comment by takeda** [comment]
Any reason why you don't want to commit the lock?

Recently `poetry2nix` removed flake.lock and I observed strange issues with updating when I was referencing it. I think not adding it is asking for trouble.

**Comment by alexshpilkin** [comment]
@takeda Not the OP, but the standard practice (*e.g.* commonly for [Node][N] and officially for [Poetry][P] and [Rust][R]) is to commit lock files for applications but not libraries, or more generally for things that in the user’s view exist independently but not for those that are dependencies. This is vague, but also logically necessary. So if we are to use Flakes for packaging libraries (which `poetry2nix` isn’t, that was probably a mistake), this issue will have to be solved somehow.

[N]: https://www.twilio.com/blog/lockfiles-nodejs
[P]: https://python-poetry.org/docs/basic-usage/#commit-your-poetrylock-file-to-version-control
[R]: https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

**Comment by takeda** [comment]
@alexshpilkin poetry2nix is technically a library, but I'm wondering if Nix supports that scenario. With flakes, even if your code acts as a library but has dependencies there's nothing preventing you from having library's dependencies fixed. That's possible, because Nix allows to have the same thing installed multiple times with different versions.

**Comment by arcnmx** [comment]
I ran into this by including a test/example flake in a subfolder of a flake repo. If I lazily reference it by `./example` instead of `path:./example` it messes with the repo staging state despite the gitignore entry :disappointed:

**Comment by alexshpilkin** [comment]
@takeda Nix can’t fix everything here.

For example, some compilers (GHC, Rust) generate binaries without a well-defined ABI even when linking dynamically, so either the consumer must be able to override the library’s locked compiler version or the build will simply be incorrect (even if for Rust things will work unless you’re unlucky, for GHC rebuilding the world on a compiler version bump is a necessity).

More generally, the linking model used by Glibc (but not macOS or Windows) is unable to tolerate different versions of the same shared library in a single address space unless the programmer goes through the required `dlopen()` contortions explicitly, so if A depends on B which compiles in a dependency on D-1 and on C which compiles in a dependency on D-2, the result will possibly run but in such a way that you’ll wish it didn’t. Even if this were supported properly, unless the developers of B and C took great care not to allow the ABI of D to leak through to their consumers the result will be broken.

Native code aside, I think Node is the only system that supports multiple versions of the same package in the same execution environment at a given time, neither Python nor Ruby nor Lua nor ... even try. Instead they *ignore* any lockfile a dependency might have in favour of the executable, thus the recommendation to omit the lockfile (and the resultant merge noise) completely unless some executables are included as well.

I have to admit I have no idea how flaky Nix approaches this, though: all of the above systems only need to work inside their own little language-specific world, while Nix may need to describe interdependent executables as well, and there it may well make sense to have several versions in play simultaneously.

**Comment by PaulGrandperrin** [comment]
OMG, thank you so much for this bug report! I thought I was going crazy!
This is extremely unexpected and doesn't respect how git is supposed to work nor the explicit choice of the user.

Please make that feature optional and disabled by default, or remove it 🙏

**Comment by PaulGrandperrin** [comment]
The problem becomes so much worse when using something like `https://github.com/nix-community/nix-direnv`.
It forces adding `flake.lock` at every single prompt, even in the middle of things like `git rebase -i`.
I got so many issues because of it, I now realize.

**Comment by PaulGrandperrin** [comment]
Does anyone know a way to force `nix` to respect `.gitignore`'s content?
(without recompiling `nix`)

**Comment by ncfavier** [comment]
If there was, this issue would be closed.

**Comment by PaulGrandperrin** [comment]
@ncfavier I not necessarily, there could be a hack to go around this issue while waiting for `nix` to be fixed for real.

**Comment by PaulGrandperrin** [comment]
Thanks a lot @edolstra for #6917 !
In the meantime, here's my hack for those interested:
```nix
      ((pkgs.writeShellApplication {
        name = "git";
        text = ''
          pname="$(ps -o comm= $PPID)"
          if [ "$pname" == "nix" ] && [ "$5" == "add" ] && [ "$6" == "--force" ] && [ "$7" == "--intent-to-add" ] && [ "$8" == "--" ] && [ "$9" == "flake.lock" ]; then
            exit 0
          else
            exec -a "$0" "${pkgs.git}/bin/git" "$@" 
          fi
        '';
      }).overrideAttrs (final: prev: {
        meta.priority = 1;
      }))
```

**Comment by AshleyYakeley** [comment]
`git add` even without `--force` still gives an error, causing `nixos-rebuild` to terminate. Is there a way to stop that? I tried `git config add.ignoreErrors true` but it doesn't help.

**Comment by PaulGrandperrin** [comment]
The bug described here has been fixed, are you sure it's the same thing?

**Comment by AshleyYakeley** [comment]
I have flake.lock in my .gitignore because I don't want to commit the lock file. Whenever I run a command that updates the lock file, it fails.

e.g. `nix flake lock`:

```
The following paths are ignored by one of your .gitignore files:
flake.lock
error: program 'git' failed with exit code 1
```

Does this count as the same issue? I still can't do the thing.

**Comment by PaulGrandperrin** [comment]
@AshleyYakeley That's indeed very similar but no it was a different issue.

The issue here was that, on the contrary, it would forcefully and silently add the `flake.lock` even if it was blacklisted in the `.gitignore`.

You can try `--no-write-lock-file` and maybe open a new issue.

**Comment by masklinn** [comment]
> You can try `--no-write-lock-file` and maybe open a new issue.

If you get here, try that, and this doesn't seem to work, it might be because some of the options are ordering-sensitive. For instance `--command` can't come before `--no-write-lock-file`, it has to come after or the command still fails.
