### ISSUE TITLE
flakes: nix shell (and similar) fails, if flakes.nix inside a git-repo ist no yet added to the repo (error: getting status of '/nix/store/.../flake.nix': No such file or directory)

### ISSUE THREAD

**Issue by systemofapwne** [NixOS/nix#6642]
If a flakes.nix file is copied to a repository (empty or with content), then without adding it yet to the reposiroty, envoking `nix shell` and other flake related commands will fail with an error like
```
error: getting status of '/nix/store/0ccnxa25whszw7mgbgyzdm4nqc0zwnm8-source/flake.nix': No such file or directory
```
rather than falling back to just use the locally available flake.nix (should be the default IMH).

**Steps To Reproduce**

1. `git init test && cd test`
2. Copy any flake.nix file in there (see e.g. my attached one)
3. run `nix shell`

**Expected behavior**

A nix shell should be opened using the locally present but not yet added or commited `flakes.nix`.

**`nix-env --version` output**
nix-env (Nix) 2.8.1

**Additional context**

The flake.nix file, that I used
```
{
  inputs.artiq.url = "git+https://github.com/m-labs/artiq.git";
  inputs.extrapkg.url = "git+https://git.m-labs.hk/M-Labs/artiq-extrapkg.git";
  inputs.extrapkg.inputs.artiq.follows = "artiq";
  outputs = { self, artiq, extrapkg }:
    let
      pkgs = artiq.inputs.nixpkgs.legacyPackages.x86_64-linux;
      aqmain = artiq.packages.x86_64-linux;
      aqextra = extrapkg.packages.x86_64-linux;
    in {
      defaultPackage.x86_64-linux = pkgs.buildEnv {
        name = "artiq-env";
        paths = [
          # ========================================
          # EDIT BELOW
          # ========================================
          (pkgs.python3.withPackages(ps: [
            # List desired Python packages here.
            aqmain.artiq
            #ps.paramiko  # needed if and only if flashing boards remotely (artiq_flash -H)
            #aqextra.flake8-artiq

            # The NixOS package collection contains many other packages that you may find
            # interesting. Here are some examples:
            ps.pandas
            ps.numpy
            ps.scipy
            #ps.numba
            #ps.matplotlib
            # or if you need Qt (will recompile):
            #(ps.matplotlib.override { enableQt = true; })
            ps.matplotlib.override { enableGtk3 = true; }
            ps.pybase64
            #ps.bokeh
            #ps.cirq
            #ps.qiskit
          ]))
          #aqextra.korad_ka3005p
          #aqextra.novatech409b
          # List desired non-Python packages here
          #aqmain.openocd-bscanspi  # needed if and only if flashing boards
          # Other potentially interesting packages from the NixOS package collection:
          #pkgs.gtkwave
          #pkgs.spyder
          #pkgs.R
          #pkgs.julia
          # ========================================
          # EDIT ABOVE
          # ========================================
        ];
      };
    };
}
```

**Comment by aakropotkin** [comment]
This is the expected behavior AFAIK

**Comment by tomberek** [comment]
Summary: I'm not aware of a simple and easy solution to this UX annoyance that does not lead to more UX problems elsewhere.

This is intended. While making this new behavior default would simplify a few situations, it will also make others more complicated. As an analogy to another technology that purports to provide reproducible source code trees (git) that does not provide a similar default behavior:

1) git init test && cd test
2) copy any file in there
3) run `git show`
See error

Perhaps the error message should be better, or there should be an easier way than `git --intent-to-add` to do what you'd like. Perhaps it should automatically include it, but with a warning that clarifies what is happening, but then we must be careful to avoid this becoming depended on and then authors accidentally leave files out of repos that are needed for evaluation to occur. Then all this behavior needs to be explained. For now, the rule is simple: "if you are in a git repo, flake evaluation only utilizes files that git is tracking."

**Comment by aakropotkin** [comment]
Honestly the fact that flakes don't automatically add files is a feature, and for me it's one of the biggest draws because of its interaction with the eval cache.

Sure sometimes I forget to add a file, but I almost always forget to `gitignore` things like `result` in a fresh repo. If files were auto added without a flag or option, the eval cache would trigger rebuilds as often as `nix-build` used to.

**Comment by systemofapwne** [comment]
> Summary: I'm not aware of a simple and easy solution to this UX annoyance that does not lead to more UX problems elsewhere.
> 
> This is intended. While making this new behavior default would simplify a few situations, it will also make others more complicated. As an analogy to another technology that purports to provide reproducible source code trees (git) that does not provide a similar default behavior:
> 
> 1. git init test && cd test
> 2. copy any file in there
> 3. run `git show`
>    See error
> 

I can understand, that this is by design and intended. I can even live with that decision. Regarding your next statement...

> Perhaps the error message should be better, or there should be an easier way than `git --intent-to-add` to do what you'd like. 

I am absolutely for that. I spent about two hours debugging this and I am and will not be the last one falling for that. The error message should be way more clearer for a better UX. 
Like
```
error: getting status of '/nix/store/0ccnxa25whszw7mgbgyzdm4nqc0zwnm8-source/flake.nix': No such file or directory
Local flake.nix found, which is not member of the repository.
```
or something similar.

**Comment by systemofapwne** [comment]
> Honestly the fact that flakes don't automatically add files is a feature, and for me it's one of the biggest draws because of its interaction with the eval cache.
> 
> Sure sometimes I forget to add a file, but I almost always forget to `gitignore` things like `result` in a fresh repo. If files were auto added without a flag or option, the eval cache would trigger rebuilds as often as `nix-build` used to.

Maybe (or certainly) I do not understand the full nix architecture in detail yet.
But I was rather referring to making flakes not fail when a flakes.nix file certainly **is there** (but not a member of a repo yet). Not automatically adding it to the repo.
Yet, as stated one post earlier, I can live with that behavior/design choice. The error message should just be more clearer, so that someone without a deep understanding of nix, flakes etc can troubleshoot the situation with a simple ``git add flakes.nix``.

**Comment by yeoldegrove** [comment]
I have the very same issue. My use case is this https://nixos.wiki/wiki/Flakes#Super_fast_nix-shell
I am using this for repos that might also be used by non-nix users that would get annoyed by adding `shell.nix` and `flake.*` files to the repos.
In the old world, I had my `shell.nix` in `.gitignore` (no `flake.nix`) and everything worked fine.
Also adding the `flake.nix` file to `.gitignore` will not be enough to get rid of "flake.nix': No such file or directory".

**Comment by aakropotkin** [comment]
> I have the very same issue. My use case is this https://nixos.wiki/wiki/Flakes#Super_fast_nix-shell
> I am using this for repos that might also be used by non-nix users that would get annoyed by adding `shell.nix` and `flake.*` files to the repos.
> In the old world, I had my `shell.nix` in `.gitignore` (no `flake.nix`) and everything worked fine.
> Also adding the `flake.nix` file to `.gitignore` will not be enough to get rid of "flake.nix': No such file or directory".

Ignoring `flake.nix` would prevent your flake from ever being available. Definitely don't add that to your ignores.

I think you misunderstood my comment about how legacy UI commands would cause spurious rebuilds because unimportant files were added to the working dir. The common workaround was various source filters, notable `nix-gitignore`. The old workflow was basically "clone a repo, extend `.gitignore` ( to the point that it's almost identical to `git clean -xfd` ), create `*.nix` using `nix-gitignore` filters, and THEN run `nix-*`.

Skipping these steps would cause Nix to rebuild projects needlessly, often to such a degree that it was easier for Nix files to be maintained externally. The new UI'S `git` integration resolves these issues. The tradeoff is "I don't have to do all that filtering, I just have to `git add flake.{nix,lock}` once and forget about it". 😉

**Comment by tomberek** [comment]
> I am absolutely for that. I spent about two hours debugging this and I am and will not be the last one falling for that. The error message should be way more clearer for a better UX.

There is a pending PR which has a better message. What do you think about this?
https://github.com/NixOS/nix/blob/5f1340219b83f15a4354aad94467ae642a1196ed/src/libfetchers/git.cc#L756-L759

**Comment by systemofapwne** [comment]
> > I am absolutely for that. I spent about two hours debugging this and I am and will not be the last one falling for that. The error message should be way more clearer for a better UX.
> 
> There is a pending PR which has a better message. What do you think about this?
> 
> https://github.com/NixOS/nix/blob/5f1340219b83f15a4354aad94467ae642a1196ed/src/libfetchers/git.cc#L756-L759

This is a welcome solution for me!

**Comment by WhatisRT** [comment]
I've also lost several hours to this issue. Since it wasn't completely non-trivial to find, the PR that contains this change is https://github.com/NixOS/nix/pull/6530. That PR is also still a draft, so I'd prefer this to stay open until it's merged.

**Comment by lheckemann** [comment]
@tomberek/@edolstra could one of you reopen this issue and put a "Closes #6642" in the PR description for #6530?

**Comment by yacinehmito** [comment]
Like @WhatisRT, I lost hours to this issue. @tomberek Please follow @WhatisRT's suggestion and reopen the issue. Thank you.

**Comment by tejing1** [comment]
This situation might be improved by making the nix CLI default to `path:.` instead of `git+file:.` when `flake.nix` is not added to git and/or is gitignored.

The usecase of adding a local `flake.nix` to a repo which would not accept it being committed upstream would be streamlined this way, though it wouldn't stamp out the unintuitive issues related to files not existing due to being untracked or ignored by git. It might even add to them, since adding `flake.nix` would change the behavior of other files in this regard.

**Comment by zippy** [comment]
That error message is indeed terrible UX, it provides no clue as to what's going on.

**Comment by aakropotkin** [comment]
> This situation might be improved by making the nix CLI default to `path:.` instead of `git+file:.` when `flake.nix` is not added to git and/or is gitignored.
> 
> The usecase of adding a local `flake.nix` to a repo which would not accept it being committed upstream would be streamlined this way, though it wouldn't stamp out the unintuitive issues related to files not existing due to being untracked or ignored by git. It might even add to them, since adding `flake.nix` would change the behavior of other files in this regard.

Now this I actually agree with.

For clarity though you should add `flake{nix, lock} ` to your repo. Yes the error message could be better ( PR it ).

**Comment by steveeJ** [comment]
> This situation might be improved by making the nix CLI default to `path:.` instead of `git+file:.` when `flake.nix` is not added to git and/or is gitignored.

in many situations that would also lead to copying lots of data into the nix store, which i would find to be a regression. people would have to readjust their habits to explicitly state `git+file.` which i certainly feel resistance towards (i.e. laziness :laughing:).

since in the case of a dirty git tree users already get a warning, i suggest to also print a warning if `flake.{nix,lock}` exist but are not racked in git.

**Comment by tejing1** [comment]
Yes, that's what I meant.

Indeed, it might be better to just pretend `flake.{nix,lock}` are tracked even when they aren't. I haven't thought it all through, but it does seem like that has less potential fallout, and avoids copying `.git` to the store all the time, too.

**Comment by jerlam06** [comment]
2 years since the issue creation and we still cannot run nix develop when the flake.* files are in gitignore? This is my company's app and do not want to commit these flake files which are not related to the project and which are only used by me. Just let me do what I want instead of imposing me this decision...

**Comment by danielpza** [comment]
@jerlam06 have you tried `nix develop path:.`?

**Comment by tejing1** [comment]
The problem is that there isn't really a good solution here.

If nix copies non-git files generally, then you end up with all kinds of detritus and intermediate files copied into the nix store, and then those intermediate files often mess up build processes because the timestamp data is gone.

If you build only from the latest actual commit then it's too annoying to quickly test out a change to a flake.

The compromise we've landed on is to use the dirty copies of any files tracked by git, but ignore other files. It's not perfect, but it's quite hard to come up with a change to it that wouldn't cost too much in terms of other unintuitive results. I'd love to see a nice solution to the usecase of adding a local flake.nix to a repo that doesn't have one upstream, but any such solution needs be considered in terms of all the effects it would have, not just that it solves that one issue.

**Comment by mightybyte** [comment]
I don't think we should be forced to overload `.gitignore` to serve this separate purpose of defining what goes into the nix store.  Maybe have that as a default, but it needs to be overridable.  I just tried using nix flakes for a new project for the first time and this is the very first use case I wanted.  I think using flake.nix to nixify a project without having to check the flake.nix file into the repo is a very important use case.

**Comment by mwoodpatrick** [comment]
I hit the same issue and was very confused by this, Fixing the error message as per the above would have really helped me and would be a very welcome change. This is an issue that should be well documented in flakes documentation. But this is the first time I have seen this behavior documented.

**Comment by zeratax** [comment]
> I hit the same issue and was very confused by this, Fixing the error message as per the above would have really helped me and would be a very welcome change. This is an issue that should be well documented in flakes documentation. But this is the first time I have seen this behavior documented.

this seems to have been fixed in https://github.com/NixOS/nix/pull/9398 but sadly isnt in the nix that ships with 24.05 :/

**Comment by systemofapwne** [comment]
> > I hit the same issue and was very confused by this, Fixing the error message as per the above would have really helped me and would be a very welcome change. This is an issue that should be well documented in flakes documentation. But this is the first time I have seen this behavior documented.
> 
> this seems to have been fixed in #9398 but sadly isnt in the nix that ships with 24.05 :/

This looks like a regression by this PR: https://github.com/kolloch/nix/commit/598deb2b23bc59df61c92ea25745d675686f3991

**Comment by maxammann** [comment]
imo this definitely needs a better error message

**Comment by imiric** [comment]
Folks, pardon my harshness, but it's absolutely insane that this issue exists in the first place.

Let's forget about the confusing error message, and assume that it's fixed at some point (though it still isn't on `25.05beta767267.6607cf789e54`). The bigger question is: _why is Nix depending on the state of my Git repository to begin with_??

I'm sure the answer is related to some deep technical reason regarding reproducibility, but surely the tool is able to figure out which files it needs for the build based on the specified inputs?

In my case I have a dead simple `flake.nix`:

```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs = { self, nixpkgs }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs { inherit system; };
    in {
      devShells.${system}.default = pkgs.mkShell {
        buildInputs = [
          pkgs.nodejs_23
        ];
      };
    };
}
```

This doesn't depend on any files in the repo. The only thing Nix needs to do is to fetch `nodejs_23` and spawn a new shell. That's it.

And even if it did depend on a file in the repo, then couldn't just those specific files be added to the input, or build context, or however you call it?

I'm sure that Docker is laughed at in this community, but when I run `docker build .` (using BuildKit), the only files included in the build context are ones referenced in the `Dockerfile`. Even before BuildKit, users had the option to use `.dockerignore` to avoid copying large files. Why can't Nix use a similar approach?

Honestly, it's these types of issues that make the Nix ecosystem so user hostile. We can argue all day whether this works as intended or not, but it objectively leads to a poor user experience. I just wish that developers of tools like this, with undeniably great technical ideas and talent, prioritized UX over everything else. :face_exhaling:

**Comment by tejing1** [comment]
The main reason nix depends on the state of the git repository, afaik, is because it can be extremely annoyingly wasteful to copy unneeded intermediate build products from local building (not to mention the whole `.git` directory!) to the nix store when evaluating a flake. For some usecases, it's downright prohibitive. And the whole concept behind flakes is built around evaluation from the nix store, so that the code being evaluated can be assured reproducible, so you have to copy it there.

At the same time, no one wants to have to commit just to evaluate a flake, so we end up with this compromise where files tracked by git are copied even if dirty, but other files are ignored.

The current solution is definitely not ideal, but it's honestly pretty hard to imagine another way to go about this that wouldn't have worse consequences.

**Comment by imiric** [comment]
Well, it's also extremely annoyingly wasteful to copy any files that are not strictly required for the build. Not to mention this annoyingly confusing behavior, and having to stage or commit the `flake.nix` file as a workaround. Outside of a very few exceptions, **no program should access any files on my filesystem that I didn't explicitly tell it to access**.

So couldn't there be a way to explicitly tell Nix which files are required for the build? In my case, no external files are required at all, yet I'm still forced to track `flake.nix` in Git for no reason.

Maybe a directive within `flake.nix` could be used to declare the external dependencies. Or viceversa, which files to ignore, as many other tools do.

I don't know, it's not my place to come up with a solution to this, and I won't pretend to know more than the developers. I'm just pointing out, along with everyone else in this issue, that the current behavior is very counterintuitive. This is not a problem that other tools in this space have, so it shouldn't be impossible to solve.

**Comment by ArchercatNEO** [comment]
It seems like the more intuitive solution should be to exclude files that match the `.gitignore` and include everything else even if it is untracked. Build artifacts should not even be considered for tracking while just files from developement very well could. Even the current situation means copying the flake with most files and requiring that files be tracked by git just means extra steps to add those files to git.

I'm not too sure how much [lazy trees](https://github.com/NixOS/nix/pull/6530) would affect local development but would they help with keeping the src small here? I see it explicitly says `src = ./.` still requires copying the entire tree but what about an expression like `src = "${self}/src"`;?

**Comment by ArchercatNEO** [comment]
> This doesn't depend on any files in the repo.

As of now, I believe this is actually *false*. `outputs` depends on `self` and `self` must be coerceble to a path. For self to have a value *something* must be copied to the store. For a flake this could copying the entire flake repo or copying just files tracked by git. Lazy trees seem like they might have some use here (and backreading led to someone saying that they would) since it means the tree may not need to be copied.

It seems like right now there are 2 reasons for why nix will not evaluate untracked files: 1) doing otherwise is potentially prohibitively unperformant and 2) doing otherwise is impure.

It would be helpful is someone with more knowledge about this could confirm/deny whether lazy trees (with proper care) could solve performance degredations (ie not copying files that aren't used in eval) by just not copying artifacts that aren't being used anyway. It seems like this was a large issue with `nix-build`(?) which lead to the current behavior. 

As for purity, we already don't have purity. A file can be added to git but if the file changes nix will impurely use the changes too. For purity we would require nix to ignore any uncommited changes which clearly is not defensible. I don't see why being less pure (ie evaluating untracked files) is a deal breaker for local flake developement. Even if we wanted we can't access uncommited changes through git fetchers so building from remote flakes is as pure as before. And the argument that blocking builds using untracked files helps to ensure that when developers push their changes all the files required for build which helps developers avoid foot-guns also doesn't seem very reasonable to me. If all my files are tracked but I made changes since then which I haven't added to the commit I can still push a commit which won't build.

I think the performance argument is reasonable (though can't tell why we shouldn't just use the `.gitignore` rather than tracked/untracked files for this) and would like a comment to whether lazy trees could solve the issue without involving the git tree. The purity argument in this situation I don't see much value in. Using untracked files doesn't make remote flakes any less pure than before and using them locally makes developer experience better. Pushing with uncommited local changes is not less of a problem if we ban untracked files but allow dirty trees and I don't think anyone wants to commit all changes just to build.

I do not propose we automatically add any files to the repo, this would break many things about the way we should expect git to behave.

**Comment by tejing1** [comment]
It's a performance (both in terms of time and disk space) issue, not really a purity one. Many alternatives can be considered equally pure in the ways that matter.

Lazy trees can *help* with the performance issue... in some cases... if you're careful with how you write your nix code. It's not a solution, by any stretch of the imagination, but it could lessen the issue somewhat.

**Comment by ArchercatNEO** [comment]
To make things clearer let's define a highly specific directory structure *which is not a git repo*.

.
|- flake.lock
|- flake.nix
|- package.nix
|- artifacts/ //contains *all* build artifacts for non-nix builds
|- src //the exclusive directory for this pkg's source

`flake.nix` references `package.nix` by using `"${self}/package.nix"` and `package.nix` has `src = "${self}/src"`. I believe that the current behaviour is to first copy all files (including the `artifacts` dir) to the store then evaluate the expressions. With lazy trees would this behaviour change or would artifacts still be copied to the store even though it is never accessed by a nix expression?

If even with lazy trees the artifacts dir is *still* copied to the store, is there *any* file structure where with lazy trees and an artifacts dir *inside* the flake's directory, this artifact dir would not be copied?

**Comment by tejing1** [comment]
> With lazy trees would this behaviour change or would artifacts still be copied to the store even though it is never accessed by a nix expression?

It would still be copied. Technically it has to be. The `src` attr needs to be set to `/nix/store/abc....789-something/src`, and the derivation could, in principle, check what's in `..`, and it needs to see the rest of the flake in that case.

What would work with lazy trees would be `src = "${./src}";`, I believe. At least, it could work without breaking semantics. Since in that case the semantics require copying just the `src` directory to its own store object. However, without lazy trees, or if the whole flake needs to be copied anyway for some other reason, this copies the contents of that directory to the nix store *twice*, which is definitely not good.

**Comment by evolutics** [comment]
For anyone running into this error with Home Manager using Nix flakes, try replacing `home-manager switch` by

```bash
cd ~/.config/home-manager
home-manager --flake path:. switch
```

to avoid skipping Git-ignored files. See also #7107.
