### ISSUE TITLE
this system does not support the kernel namespaces that are required for sandboxing

### ISSUE THREAD

**Issue by johnrichardrinehart** [NixOS/nix#7783]
# Description

Between 8ab9fda and c192151 my ability to upgrade my system and use my `direnv` flakes has been broken with the following
```bash
$ direnv allow
direnv: loading ~/code/repos/others/some-org/frontend/.envrc                                                                                                                
direnv: using flake
warning: Git tree '/home/john/code/repos/others/some-org/frontend' is dirty
error: this system does not support the kernel namespaces that are required for sandboxing; use '--no-sandbox' to disable sandboxing
warning: Git tree '/home/john/code/repos/others/some-org/frontend' is dirty
direnv: nix-direnv: renewed cache
```

Looking at the commit history between these two commits it's clear that this is somewhat intentional/expected: Additional checks are being added to ensure that a `linux` host has cgroup namespace support enable in their kernel. But, is it expected that this should, by default, break existing environments?

If there is already a discussion or documentation about this intended breaking change and how to fix it then I'd be happy to be provided a URL and I'll go RTFM. I wanted to create this issue since I couldn't find any other place online, yet, where anyone has discussed this problem and it's solution. In the interim I've `nixos-rebuild switch --rollback`ed.

**Comment by NobbZ** [comment]
I have to confirm, I am not able to build anything as well.

This only affects real "builds".

My observations so far:

1. `nix build` for a locally existing path suceeds.
2. `nix build` for something that is fully substitutable from the cache(s) suceeds
3. `nix build` for something that is missing (or forces a rebuild eg. with `--rebuild`) will fail with the above mentioned error
4. `--no-sandbox` does not help! (well, with `sudo` it does, so may be a trusted user option)

On my system I use a plain kernel without any modifications:

https://github.com/NobbZ/nixos-config/blob/b73464577e1d2ccda652f26516c98ea6f89e175b/nixos/modules/kernel.nix#L9-L13

Tested only on mimas so far:

```
$ uname -a
Linux mimas 6.1.8 #1-NixOS SMP PREEMPT_DYNAMIC Tue Jan 24 06:24:44 UTC 2023 x86_64 GNU/Linux
```

We realised already in another communication channel, that John and I both have binfmt configured.

My secondary system that is not configured for binfmt is currently building the newer nix version for a test. Though that system is a decade old and takes at least 2 hours for building nix alone (and 20+ minutes to evaluate the system configuration).

**Comment by johnrichardrinehart** [comment]
It's interesting. I leap-frogged to
```bash
$ nix --version
nix (Nix) 2.14.0pre20230208_e4a2a5c
```
after toggling
```bash
$ rg 'binfmt' . 
./modules/configuration.nix
15:  boot.binfmt.emulatedSystems = [ "aarch64-linux" ];
```
and can no longer reproduce. To be clear, `binfmt` is now enabled so I now have `/proc` mount for `binfmt` like `nix` checks to see if `/proc` is "fully visible".
```bash
$ grep '\/proc' /proc/mounts
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=58,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=236 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,nosuid,nodev,noexec,relatime 0 0
```
So, maybe this problem has been fixed sometime today?

**Comment by johnrichardrinehart** [comment]
Looks like this is related to `binfmt` being enabled and whether or not `/proc` is fully visible. Removing 
```bash
$ rg 'binfmt' .                           
./modules/configuration.nix
15:  boot.binfmt.emulatedSystems = [ "aarch64-linux" ];
```
from my configuration resolves these issues:
```bash
$ grep '\/proc' /proc/mounts | grep binfmt | wc -l
0
```
This was non-zero before commenting out the `binfmt` line in my system config, just to be clear.

**Comment by NobbZ** [comment]
> It's interesting. I leap-frogged to
>
> $ nix --version
> nix (Nix) 2.14.0pre20230208_e4a2a5c

For me it still fails using this commit.

It seems to be important that the demon is running that version! Just using `nix shell` is not enough.

**Comment by johnrichardrinehart** [comment]
> > It's interesting. I leap-frogged to
> > $ nix --version
> > nix (Nix) 2.14.0pre20230208_e4a2a5c
> 
> For me it still fails using this commit.
> 
> It seems to be important that the demon is running that version! Just using `nix shell` is not enough.

Sorry about that. I deleted that comment because it appears it's not true that leap-frogging fixed it.

**Comment by NobbZ** [comment]
I started to bisect the issue yesterday, and it just confirms the commit we already had under suspicion:

```
bc1d9fd8b5a14334af1d0455e6b4d595cae959d5 is the first bad commit
commit bc1d9fd8b5a14334af1d0455e6b4d595cae959d5
Author: Eelco Dolstra <edolstra@gmail.com>
Date:   Fri Jan 27 15:25:56 2023 +0100

    Check whether we can use PID namespaces
    
    In unprivileged podman containers, /proc is not fully visible (there
    are other filesystems mounted on subdirectories of /proc). Therefore
    we can't mount a new /proc in the sandbox that matches the PID
    namespace of the sandbox. So this commit automatically disables
    sandboxing if /proc is not fully visible.

 src/libstore/build/local-derivation-goal.cc |  6 ++---
 src/libutil/namespaces.cc                   | 37 +++++++++++++++++++++++++----
 src/libutil/namespaces.hh                   |  2 ++
 3 files changed, 37 insertions(+), 8 deletions(-)
```

This is what is mounted under `/proc`, the name of the mounts again confirms what John already figured by disabling `binfmt`:

```
$ grep proc /proc/mounts
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=62,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=12093 0 0
binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,nosuid,nodev,noexec,relatime 0 0
```

<details>
  <summary>Bisect log</summary>

```
git bisect start
# status: waiting for both good and bad commits
# bad: [e4a2a5c074f8faf947a8864ca2acea85a8fc6ab7] Documentation:  builtins.fetchGit when used on a local path (#7706)
git bisect bad e4a2a5c074f8faf947a8864ca2acea85a8fc6ab7
# status: waiting for good commit(s), bad commit known
# good: [895dfc656a21f6252ddf48df0d1f215effa04ecb] Merge pull request #7705 from Ma27/fix-initNix-in-perl-bindings
git bisect good 895dfc656a21f6252ddf48df0d1f215effa04ecb
# bad: [d834de2894b5addc5a4a8c5088debd56a8517db1] Fix macOS build
git bisect bad d834de2894b5addc5a4a8c5088debd56a8517db1
# good: [ffa9feee88459e4177acdda35aea130aa05eb428] Merge pull request #7766 from NixOS/dependabot/github_actions/cachix/install-nix-action-19
git bisect good ffa9feee88459e4177acdda35aea130aa05eb428
# good: [1ba13b17db1d2ff4342b41cbd610b76060582335] Merge pull request #7758 from peterbecich/clang11-devshell-documentation
git bisect good 1ba13b17db1d2ff4342b41cbd610b76060582335
# bad: [bc1d9fd8b5a14334af1d0455e6b4d595cae959d5] Check whether we can use PID namespaces
git bisect bad bc1d9fd8b5a14334af1d0455e6b4d595cae959d5
# good: [fb2f7f5dcc6b37a4f39f59d9f477d3fa57d79095] Fix auto-uid-allocation in Docker containers
git bisect good fb2f7f5dcc6b37a4f39f59d9f477d3fa57d79095
# first bad commit: [bc1d9fd8b5a14334af1d0455e6b4d595cae959d5] Check whether we can use PID namespaces
```

`nix build .` was used to build the individual nix version.

`sudo ./result/bin/nix build nixpkgs#hello --rebuild` to force a build, circumventing the deamon.
</summary>

**Comment by johnrichardrinehart** [comment]
> I started to bisect the issue yesterday, and it just confirms the commit we already had under suspicion bc1d9fd8b5a14334af1d0455e6b4d595cae959d5:
> 
> ```
> bc1d9fd8b5a14334af1d0455e6b4d595cae959d5 is the first bad commit
> commit bc1d9fd8b5a14334af1d0455e6b4d595cae959d5
> Author: Eelco Dolstra <edolstra@gmail.com>
> Date:   Fri Jan 27 15:25:56 2023 +0100
> 
>     Check whether we can use PID namespaces
>     
>     In unprivileged podman containers, /proc is not fully visible (there
>     are other filesystems mounted on subdirectories of /proc). Therefore
>     we can't mount a new /proc in the sandbox that matches the PID
>     namespace of the sandbox. So this commit automatically disables
>     sandboxing if /proc is not fully visible.
> 
>  src/libstore/build/local-derivation-goal.cc |  6 ++---
>  src/libutil/namespaces.cc                   | 37 +++++++++++++++++++++++++----
>  src/libutil/namespaces.hh                   |  2 ++
>  3 files changed, 37 insertions(+), 8 deletions(-)
> ```
> 
> This is what is mounted under `/proc`, the name of the mounts again confirms what John already figured by disabling `binfmt`:
> 
> ```
> $ grep proc /proc/mounts
> proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
> systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=62,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=12093 0 0
> binfmt_misc /proc/sys/fs/binfmt_misc binfmt_misc rw,nosuid,nodev,noexec,relatime 0 0
> ```
> 
> <details>
>   <summary>Bisect log</summary>
> 
> ```
> git bisect start
> # status: waiting for both good and bad commits
> # bad: [e4a2a5c074f8faf947a8864ca2acea85a8fc6ab7] Documentation:  builtins.fetchGit when used on a local path (#7706)
> git bisect bad e4a2a5c074f8faf947a8864ca2acea85a8fc6ab7
> # status: waiting for good commit(s), bad commit known
> # good: [895dfc656a21f6252ddf48df0d1f215effa04ecb] Merge pull request #7705 from Ma27/fix-initNix-in-perl-bindings
> git bisect good 895dfc656a21f6252ddf48df0d1f215effa04ecb
> # bad: [d834de2894b5addc5a4a8c5088debd56a8517db1] Fix macOS build
> git bisect bad d834de2894b5addc5a4a8c5088debd56a8517db1
> # good: [ffa9feee88459e4177acdda35aea130aa05eb428] Merge pull request #7766 from NixOS/dependabot/github_actions/cachix/install-nix-action-19
> git bisect good ffa9feee88459e4177acdda35aea130aa05eb428
> # good: [1ba13b17db1d2ff4342b41cbd610b76060582335] Merge pull request #7758 from peterbecich/clang11-devshell-documentation
> git bisect good 1ba13b17db1d2ff4342b41cbd610b76060582335
> # bad: [bc1d9fd8b5a14334af1d0455e6b4d595cae959d5] Check whether we can use PID namespaces
> git bisect bad bc1d9fd8b5a14334af1d0455e6b4d595cae959d5
> # good: [fb2f7f5dcc6b37a4f39f59d9f477d3fa57d79095] Fix auto-uid-allocation in Docker containers
> git bisect good fb2f7f5dcc6b37a4f39f59d9f477d3fa57d79095
> # first bad commit: [bc1d9fd8b5a14334af1d0455e6b4d595cae959d5] Check whether we can use PID namespaces
> ```
> 
> `nix build .` was used to build the individual nix version.
> 
> `sudo ./result/bin/nix build nixpkgs#hello --rebuild` to force a build, circumventing the deamon.
> </summary>

Thanks a lot for doing the hard work to confirm the source of the problem!

**Comment by NobbZ** [comment]
Today I learned that this would probably affect a couple of users, who might not even be aware of using `binfmt` at all, nor having a way to disable it.

It seems as if the WSL uses `binfmt` to allow execution of windows binaries from within the WSL.

I have not yet found someone who was able to verify this in practice for me.
